name: Update README with Repository List

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Fetch GitHub repositories
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Fetch repositories and create a simple list
        curl -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/user/repos?per_page=100" | \
        jq -r '.[] | "* [\(.name)](\(.html_url))"' > repos.md

        # Update README.md with the repo list
        sed -i '/<!-- REPO LIST START -->/,/<!-- REPO LIST END -->/c\<!-- REPO LIST START -->\n'"$(cat repos.md)"'\n<!-- REPO LIST END -->' README.md

    - name: Commit and push if README changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add README.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update README with latest repository list" && git push)
