name: Fetch GitHub User Profile

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'GitHub username to fetch details for'
        required: true
        default: 'octocat'

jobs:
  fetch-user-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch user profile
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python - <<EOF
          import requests
          import json
          import os

          username = '${{ github.event.inputs.username }}'
          token = os.environ['GITHUB_TOKEN']

          headers = {
              'Authorization': f'token {token}',
              'Accept': 'application/vnd.github.v3+json'
          }

          response = requests.get(f'https://api.github.com/users/{username}', headers=headers)
          user_data = response.json()

          print("User Profile Details:")
          print(json.dumps(user_data, indent=2))

          # Fetch additional details like repositories, organizations, etc.
          print("\nRepositories:")
          repos_response = requests.get(f'https://api.github.com/users/{username}/repos', headers=headers)
          repos_data = repos_response.json()
          print(json.dumps(repos_data, indent=2))

          print("\nOrganizations:")
          orgs_response = requests.get(f'https://api.github.com/users/{username}/orgs', headers=headers)
          orgs_data = orgs_response.json()
          print(json.dumps(orgs_data, indent=2))
          EOF

      - name: Output user profile details
        run: |
          echo "User profile details have been fetched and displayed in the job output."
