name: User Profile Details

on:
  workflow_dispatch:

jobs:
  show-user-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GitHub Actions environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install axios

      - name: Get user profile
        run: |
          node ./get-user-profile.js

      - name: Output user profile details
        run: echo ${{ steps.get-user-profile.outputs.profile }}
